from enum import Enum
class ActionType(Enum):
    LOGIN=1
    START_RECORD = 2
    STOP_RECORD = 3
    OPEN_RECORD=4,
    START_MEETING=5,
    STOP_MEETING=6,
    DISCUSS_REQUEST=7,
    ACCESS_DISCUSS=8,
    REJECT_DISCUSS=9,
    MUTE_ALL=10,
    START_FREE_DISCUSS=11,
    STOP_FREE_DISCUSS=12,
    START_MEETING_VOTE=13,
    STOP_MEETING_VOTE=14,
    LIKE_MEETING_VOTE=15,
    UNLIKE_MEETING_VOTE=16